POST http://localhost:8080/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNha0BnbWFpbC5jb20iLCJleHAiOjE3NTM0NTcxNzYsInVzZXJpZCI6NX0.WNvqI132eV-CU8AzZpDa5kz2FJrW1WvIlsizrWuuwk4

 
{

"Title":       "Spaghetti Carbonara",
"Description": "Classic Italian pasta dish with eggs, cheese, pancetta, and pepper.",
"Instruction": "1. Boil pasta\n2. Cook pancetta\n3. Mix eggs and cheese\n4. Combine all"

}

