GET  http://localhost:8080/recipe/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNha0BnbWFpbC5jb20iLCJleHAiOjE3NTM1MTA0ODAsInVzZXJpZCI6NX0.m6YCYFaIxzhAzBIypHnw5pAOpUeX8zj6Z-lN0NmIkW8
